pp-2023/src/app/kmeans/client-elements-customized-input.js, pp-2023/src/app/kmeans/client-elements-default-input.js, pp-2023/src/app/utils/kmeans.js
Feature hinzugefügt, dass ein User manuell Datenpunkte eingeben kann. Dabei bildet sich die aktuelle Logik wie folgt ab. Der User kann mit einem Buttonklick steuern, wie viele Punkte er eingeben will, 2 oder 3. Nach einer Eingabe ist das wechseln nicht mehr möglich. Es können beliebig viele weitere Punkte über den Add Button hinzugefügt werden. 
Geprüft werden kann das Array welches gebaut wird aktuell nur über folgendes Vorgehen:
auf den Branch PROG-14-manuelle.. wechseln. In die Funktion handleButtonAdd gehen, und folgende Zeile eingeben. 
console.log(inputDataArray);
Einen "richtigen" ConsolenBefehl würde ich hinzufügen im Zuge des Refactorings Client-Elements-Default-Input.js
=> Prog 14 manuelle dateneingabe

Dockerfile
Dockerfile muss in den Ordner damit die Pipe funktioniert. Pipeline ist ansonsten Funktionsfähig.
=> Added Dockerfile for CI / CD

pp-2023/Dockerfile
=> Dev branch + dockerfile

pp-2023/src/app/globals.css, pp-2023/src/app/impressum/page.js
Einmal bitte gucken, ob der Text an sich passt und eventuell Verbesserungsvorschläge direkt schreiben
=> feat: added impressum text

pp-2023/src/app/globals.css, pp-2023/src/app/kmeans/create-save-manuel-input.js, pp-2023/src/app/kmeans/switch-variables.js
Rework des Buttons zum Switchen der Variablen. Der Button wird jetzt über einen direkten DOM-Zugriff disabled. Ich hatte hierbei Probleme mit Globalen-Statusvariablen.
=> Prog 49 rework button change variables

pp-2023/src/app/globals.css, pp-2023/src/app/kmeans/scatter-chart.js, pp-2023/src/app/page.js
Ist nicht die schönste Lösung, aber sonst ist das zu viel Zeitaufwand
=> feat: set chart fixed and maximum size

pp-2023/src/app/kmeans/switch-variables.js
Fix, der Button disabled jetzt immer, wenn eine Eingabe erfolgt ist.
=> fix: der Button diabled jetzt in jedem Fall

.idea/workspace.xml, pp-2023/package-lock.json, pp-2023/package.json
neue Version vom Excel-Reader die das Sicherheitsrisiko gelöst hat. Ist nicht ganz offiziell von npmjs aber was solls.
=> updated excel file reader

pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/requestAPI.js, pp-2023/src/app/utils/userErrors.js
Der Berechnen Button ist komplett umgesetzt. Bitte anschließend durch den PO testen. Die Ergebnisse der Berechnungen können in der Console angezeigt werden.
=> Prog 81 api call in die logik implementieren

pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/requestAPI.js, pp-2023/src/app/utils/userErrors.js
Eine Funktion die ausliest, wie lang die eingegebenen Daten sind und wie groß K ist. 
Benötigt PROG-81 um voll implementiert zu werden.
=> feature: Funktion zur Überprüfung auf die Länge der eingegebenen Daten.

pp-2023/src/app/globals.css, pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/local-remote-button.js, pp-2023/src/app/page.js
Verfügbarmachung der Probs im Calculate Button.
=> feature: Refactoring Local/Remote Button.

pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/requestAPI.js
- fix mit der Validierung der Dateilänge.
=> Fix local remote button

pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/requestAPI.js
das Backendteam hat einen Fehler behoben.
Sollte der noch einmal auftreten behandel ich den jetzt mit einer User Ausgabe.
=> Fix fehlermeldung unlsebare datei backend

pp-2023/src/app/kmeans/requestAPI.js
Fix API-Dev auf API-Live Umgebung
=> fix: API-Dev-Umgebung auf Live angepasst.

pp-2023/src/app/globals.css, pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/exportButton.js
Sowohl Lokal als auch die Berechnung der API kann ausgegeben werden. Zum Zeitpunkt des Pull Request gibt die API allerdings noch fehlerhafte Werte zurück.
=> Export der Ergebnisse über "Export Result" Button added

README.md, pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/exportButton.js, pp-2023/src/app/kmeans/generateDatasets.js, pp-2023/src/app/kmeans/scatter-chart.js
Auch die Ergebnisse der Remote Berechnungen werden jetzt im CHART angezeigt.
=> Prog 94 chart for remote calc

pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/scatter-chart.js
Das Result wurde bei File upload und remote berechnung nicht übergeben -> jetzt schon :3
=> fix: result to export button

pp-2023/src/app/globals.css, pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/elbow-kriteria.js, pp-2023/src/app/page.js
Lokale Implementierung von den Elbow Kriterium.
=> Prog 92 elbow criteria

pp-2023/__tests__/requestAPI.test.js, pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/elbow-kriteria.js, pp-2023/src/app/kmeans/requestAPI.js, pp-2023/src/app/page.js
API-Call für das Elbow-Criteria.
=> Prog 99 api call elbow

.idea/workspace.xml, pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/utils/excelfilereader.js
Ab sofort machen alle Buchstaben und Sonderzeichen keine Probleme mehr und können eingelesen werden. Nur die Thematik mit den Dimensionen für die Datensätze hab ich jetzt als Fehler in einem Alert ausgegeben. Es werden pro Reihe alle zusammenhängenden Zahlen als Wert (Dimension) übergeben. Wenn die Dimensionen nicht für alle Datensätze übereinstimmen kommt die Fehlermeldung.
=> fixed reading csv-files & xlsx files

pp-2023/src/app/context/downloadContext.js, pp-2023/src/app/kmeans/calculateButton.js, pp-2023/src/app/kmeans/downloadChartButton.js, pp-2023/src/app/kmeans/generateDatasets.js, pp-2023/src/app/kmeans/scatter-chart.js, pp-2023/src/app/page.js
bitte nochmal testen :) sollte aber eigentlich gehen
=> Prog 20 download chart new

.idea/workspace.xml, pp-2023/src/app/kmeans/create-save-manuel-input.js
Bei der manuellen Eingabe wird jetzt die jeweilige Achse als Placeholder angezeigt. Außerdem werden die Anzahl der Variablen hochgezählt. Bitte manuelle Eingabe nochmal testen falls ich was vergessen haben sollte.
=> Redesigned manuel Variable Input
